obj-m := smoke_bomb.o

smoke_bomb-y += sb_lkm.o
smoke_bomb-y += addr.o

ccflags-y += -D_SMOKE_BOMB_LKM
#ccflags-y += -D_SMOKE_BOMB_DEBUG

ccflags-y += -D_SMOKE_BOMB_ARMV8
smoke_bomb-y += ../$(ARCH)/patch.o
smoke_bomb-y += ../$(ARCH)/insn.o

default:
	$(MAKE) -C $(KDIR) SUBDIRS=$(shell pwd) modules

clean:
	rm -rf *.o *.ko *.mod *.symvers *.order *.mod.c .*cmd .tmp*

